// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro 23815987fd5c65de1306066d8380981c5ec77123
// - protoc              v3.19.4
// source: service/debug/stats/proto/debug.proto

package proto

import (
	api "c-z.dev/go-micro/api"
	client "c-z.dev/go-micro/client"
	server "c-z.dev/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// NewStatsEndpoints API Endpoints for Stats service
func NewStatsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// StatsService is the client API for Stats service.
type StatsService interface {
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...client.CallOption) (*WriteResponse, error)
	Stream(ctx context.Context, in *StreamRequest, opts ...client.CallOption) (Stats_StreamService, error)
}

type statsService struct {
	c    client.Client
	name string
}

func NewStatsService(name string, c client.Client) StatsService {
	return &statsService{
		c:    c,
		name: name,
	}
}

func (c *statsService) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.name, "Stats.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsService) Write(ctx context.Context, in *WriteRequest, opts ...client.CallOption) (*WriteResponse, error) {
	req := c.c.NewRequest(c.name, "Stats.Write", in)
	out := new(WriteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsService) Stream(ctx context.Context, in *StreamRequest, opts ...client.CallOption) (Stats_StreamService, error) {
	req := c.c.NewRequest(c.name, "Stats.Stream", &StreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &statsServiceStream{stream}, nil
}

type Stats_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamResponse, error)
}

type statsServiceStream struct {
	stream client.Stream
}

func (x *statsServiceStream) Close() error {
	return x.stream.Close()
}

func (x *statsServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *statsServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *statsServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *statsServiceStream) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// StatsHandler is the server API for Stats service.
type StatsHandler interface {
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Write(context.Context, *WriteRequest, *WriteResponse) error
	Stream(context.Context, *StreamRequest, Stats_StreamStream) error
}

func RegisterStatsHandler(s server.Server, hdlr StatsHandler, opts ...server.HandlerOption) error {
	type stats interface {
		Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error
		Write(ctx context.Context, in *WriteRequest, out *WriteResponse) error
		Stream(ctx context.Context, stream server.Stream) error
	}
	type Stats struct {
		stats
	}
	h := &statsHandler{hdlr}
	return s.Handle(s.NewHandler(&Stats{h}, opts...))
}

type statsHandler struct {
	StatsHandler
}

func (h *statsHandler) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.StatsHandler.Read(ctx, in, out)
}

func (h *statsHandler) Write(ctx context.Context, in *WriteRequest, out *WriteResponse) error {
	return h.StatsHandler.Write(ctx, in, out)
}

func (h *statsHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.StatsHandler.Stream(ctx, m, &statsStreamStream{stream})
}

type Stats_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamResponse) error
}

type statsStreamStream struct {
	stream server.Stream
}

func (x *statsStreamStream) Close() error {
	return x.stream.Close()
}

func (x *statsStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *statsStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *statsStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *statsStreamStream) Send(m *StreamResponse) error {
	return x.stream.Send(m)
}
